#!/bin/bash

# 更新系統
echo "更新系統..."
sudo apt update && sudo apt upgrade -y

# 安裝所需包
echo "安裝所需的包..."
sudo apt install -y \
  apache2 \             # Apache 網頁伺服器
  nautilus \            # 文件管理器
  php \                 # PHP 編程語言
  snapd \               # Snap 包管理工具
  mariadb-server        # MariaDB 數據庫管理系統

# 完成提示
echo "所有指定包安裝完成！"
